image: ruby:2.7

services:
  - selenium/standalone-chrome

variables:
  BUNDLE_PATH: "/bundle"


before_script:
  - gem install bundler
  - bundle install

test:
  stage: test
  script:
    - bundle exec rspec
  artifacts:
    paths:
      - report.xml
    reports:
      junit: report.xml
  only:
    - master
